package:
    type:           yii2-extension
    name:           yii2-theme-hyde
    title:          Hyde Theme for hiqdev/yii2-thememanager
    headline:       Yii2 Hyde Theme
    keywords:       hyde, theme, extension, yii2
    namespace:      hiqdev\themes\hyde
    description:    |
        This package provides [Hyde theme](https://github.com/poole/hyde)
        for [Yii2 framework](http://yiiframework.com).
